### PR TITLE
Proposal 50: Learn the IMA keyrings and keys from the log

### PR DESCRIPTION
**Pull request by stefanberger**
Signed-off-by: Stefan Berger <stefanb@linux.ibm.com>

### CODE REVIEW

**Comment by THS-on** [comment]
@stefanberger can you add how the feature is now actually implemented to this PR? Once this is done we should merge it.

**Comment by stefanberger** [comment]
> @stefanberger can you add how the feature is now actually implemented to this PR? Once this is done we should merge it.

From the enhancement:

"IMA's policy implements support for policy rules that cause keys loaded onto kernel
keyrings to be logged in the IMA measurement log in 'ima-buf' entries. This now
provides the opportunity to also learn the keys that IMA is using for signature verification
from these 'ima-buf' entries, where the DER-encoded public key is reported as part
of the measurement log entry. The learned keys can then be used to verify the
subsequent signatures found in the log.

...


#### Story 1

A system administrator using an IMA policy rule like the following does not
need to manage a system's IMA signature verification keys anymore since Keylime
will learn about the existence of the .ima keyring and the keys loaded onto it.

   measure func=KEY_CHECK keyrings=.ima"

**Comment by stefanberger** [comment]
FYI: For better documentation for this particular feature I tried it with Fedora 38 that should be farthest along. I wouldn't want to extend the docs with description that one has to build a kernel etc.

If you have not installed IMA signatures on all files do the following:

```
sudo dnf -y install rpm-plugin-ima
sudo dnf -y reinstall \*
```

You must run the system with Linux boot command line option `ima_template=ima-sig` so that IMA signatures become part of the measurement log. There's no need to enable signature enforcement on the system, measuring is good enough. For this edit /etc/default/grub to have a line like this:

```
GRUB_CMDLINE_LINUX="rhgb quiet ima_template=ima-sig"
```
Then run the following:

```
grub2-mkconfig -o /boot/grub/grub.conf
```

Set the following IMA policy in /etc/ima/ima-policy:

```
dont_measure fsmagic=0x9fa0
dont_measure fsmagic=0x62656572
dont_measure fsmagic=0x64626720
dont_measure fsmagic=0x01021994
dont_measure fsmagic=0x1cd1
dont_measure fsmagic=0x42494e4d
dont_measure fsmagic=0x73636673
dont_measure fsmagic=0xf97cff8c
dont_measure fsmagic=0x27e0eb
dont_measure fsmagic=0x6e736673
measure func=KEY_CHECK keyrings=.ima
measure func=BPRM_CHECK
measure func=FILE_MMAP mask=MAY_EXEC
```

Then reboot the system.

So far so good, but unfortunately the key that somehow is loaded into the Linux kernel seems to be the wrong one at the moment:

```
keyctl show %keyring:.ima                                                     Keyring
 938588217 ---lswrv      0     0  keyring: .ima
 459932351 ---lswrv      0     0   \_ asymmetric: Fedora kernel signing key: 76091380b4f96da2b73f660a58bb88e908ecd7ff
```

This key has id 0x08ecd7ff -- last 4 digits of the subject key id. What is need is a key with id 0xe7b0c859. Pick this from security.ima after the 3 bytes:

```
getfattr -m ^ -e hex --dump /usr/bin/swtpm
getfattr: Removing leading '/' from absolute path names
# file: usr/bin/swtpm
security.ima=0x030204e7b0c859004830460221008ca4e6c3451b3b1739f0cdfddba4a4c5c7891d6ea816d83184520541d78124b4022100b6a199eeedc91f38a39a3acfda2f1cbf1f67a8f6f26bea3242b3b6a6f33c8786
security.selinux=0x73797374656d5f753a6f626a6563745f723a737774706d5f657865635f743a733000
```

So we cannot currently learn the keyring...

This is now as good as it gets for the runtime policy on Fedora 38:
```
keylime_create_policy -k -m <(cat /sys/kernel/security/ima/ascii_runtime_measurements | grep -E "(keylime|jq|boot_aggregate|libgpgme|livesys|uresourced|gpgme\.cpython-311)") -o mypolicy.json -A fedora-38-ima.pem -i .ima
```

The boot_aggregate is expected to having to be added. keylime is there because I installed it from the sources and it's not signed, and then there are some files that don't come with signatures, like the jq package/tool for example. This spoils it.

In the end it's a rather small policy that works on my system with the stuff that I started but key learning doesn't work because the wrong key is loaded into the kernel and then it doesn't verify anything. Also, some packages come without signatures. If all packages came with signatures only adding the boot_aggregate as the single hash should be sufficient.

**Comment by stefanberger** [comment]
Tracking this via BZs:
- https://bugzilla.redhat.com/show_bug.cgi?id=2231396
- https://bugzilla.redhat.com/show_bug.cgi?id=2231404

**Comment by stefanberger** [comment]
Are there any more comments on this or can we merge this?

**Review by THS-on — APPROVED** [review]

**Comment by THS-on** [comment]
@stefanberger LGTM. If there are no comments in the next couple of days lets merge it.

**Comment by THS-on** [comment]
While there still seems to be issues in the distros to actually fully use it, I'll merge it now as this feature is part of Keylime now for a while and documented.

**Pull request merged**
